name: Dispatch Test

on:
  repository_dispatch:
    types:
      - dispatch-test

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: ./v1/
          destination: s3://soomgo-assets/icons/v1/
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_region: ap-northeast-2
          flags: --recursive

