name: Dispatch Test

on:
  repository_dispatch:
    types:
      - dispatch-test

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        name: Configure AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2
      - name: Copy Folder
        run: |
          aws s3 cp s3://soomgo-assets/icons/v1/ . --recursive
      - name: Verify Folder
        run: |
          echo "Verify folder"

