name: Dispatch Test

on:
  repository_dispatch:
    types:
      - dispatch-test

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: 'soomgo-assets'
          source_dir: 'test'
          destination_dir: 'icons'